apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
  namespace: ${KUBERNETES_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${IMAGE_NAME}
        # imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: AUTHOR
          value: kohei
        - name: VERSION
          value: ${CI_COMMIT_SHORT_SHA}
        - name: TZ
          value: Tokyo
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ${APPLICATION_NAME}
#   namespace: ${KUBERNETES_NAMESPACE}
# spec:
#   ports:
#   - port: 80
#     nodePort: ${KUBERNETES_PORT_PROD_1}
#   selector:
#     app: ${APPLICATION_NAME}
#   type: NodePort
# ---
